[FSPE-5902] Create Accessibility documentation
CenturyLinkCloud/ux-chi pull request #698
Opened 2020-09-15 17:11 UTC by jllr

2020-09-15 17:36 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://72cf8625ab8920745f01b01db26ce7f233905f63-chi-pr.enterprise.ctl.io" target="_blank"> https://72cf8625ab8920745f01b01db26ce7f233905f63-chi-pr.enterprise.ctl.io </a>

2020-09-15 17:36 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1286/ for more details.

2020-09-21 16:24 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://5aee08fa81759195ea36b65c2e84626a01a3b3d4-chi-pr.enterprise.ctl.io" target="_blank"> https://5aee08fa81759195ea36b65c2e84626a01a3b3d4-chi-pr.enterprise.ctl.io </a>

2020-09-21 16:24 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1291/ for more details.

2020-09-30 16:35 UTC, mattnickles reviewed
@jllr Are you still working on organizing the Accessibility nav items into a third tier under Foundations?

2020-10-01 10:56 UTC, jllr commented
@mattnickles I am not working on that as we had to talk about it, I sent the first PR with the documentation only. Let's discuss it later.

2020-11-25 11:08 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://4204eee64a48f4198006c4d8db5d7d47201b667b-chi-pr.enterprise.ctl.io" target="_blank"> https://4204eee64a48f4198006c4d8db5d7d47201b667b-chi-pr.enterprise.ctl.io </a>

2020-11-25 11:09 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1632/ for more details.

2020-11-27 17:27 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://d693a5528eed5dfe77ce619f11931f7847c3a2c1-chi-pr.enterprise.ctl.io" target="_blank"> https://d693a5528eed5dfe77ce619f11931f7847c3a2c1-chi-pr.enterprise.ctl.io </a>

2020-11-27 17:28 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1634/ for more details.

2020-12-04 11:38 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://cdf18a40896673292562530a9479aa509cff3979-chi-pr.enterprise.ctl.io" target="_blank"> https://cdf18a40896673292562530a9479aa509cff3979-chi-pr.enterprise.ctl.io </a>

2020-12-04 11:38 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1652/ for more details.

2020-12-08 17:48 UTC, mattnickles requested changes

2020-12-08 17:48 UTC, mattnickles commented on src/website/layouts/partials/sidenav.pug
> +                          i.chi-icon.icon-chevron-down
```suggestion
                          i.chi-icon.icon-chevron-down.-xs
```

2020-12-08 17:48 UTC, mattnickles commented on src/website/layouts/partials/sidenav.pug
> +                            li(class=`${'foundations/overview' === path ? "-active" : ""}`)
Let's change the paths for all accessibility pages to include accessibility. e.g. `${rootPath}foundations/accessibility/overview`
`${rootPath}foundations/accessibility/using-keyboard`
`${rootPath}foundations/accessibility/page-structure`

2020-12-08 17:51 UTC, mattnickles commented on src/website/views/foundations/overview.pug
> +  | CenturyLink is required to meet the Web Content Accessibility Guidelines (<a target="_blank" href="https://www.w3.org/TR/WCAG20/">WCAG 2.0</a>), Conformance
```suggestion
  | Lumen is required to meet the Web Content Accessibility Guidelines (<a target="_blank" href="https://www.w3.org/TR/WCAG20/">WCAG 2.0</a>), Conformance
```

2020-12-08 17:57 UTC, mattnickles commented on src/website/layouts/partials/sidenav.pug
> +                          .chi-accordion__title #{section.title}
Style is slightly off here in mobile. Accessibility is rendering as a Level 1 item versus Level 2 on desktop.

2020-12-08 17:58 UTC, mattnickles commented on src/website/layouts/partials/sidenav.pug
> +                          i.chi-icon.icon-chevron-down
```suggestion
                          i.chi-icon.icon-chevron-down.-xs
```

2020-12-11 17:44 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f08dc008aa0e0d673b176ae713ece61d74c33d79-chi-pr.enterprise.ctl.io" target="_blank"> https://f08dc008aa0e0d673b176ae713ece61d74c33d79-chi-pr.enterprise.ctl.io </a>

2020-12-11 17:45 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1655/ for more details.

2020-12-15 18:52 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://17c2a2c06244b0642f48bdf014590c763b5ea7b9-chi-pr.enterprise.ctl.io" target="_blank"> https://17c2a2c06244b0642f48bdf014590c763b5ea7b9-chi-pr.enterprise.ctl.io </a>

2020-12-15 18:53 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1660/ for more details.

2020-12-16 19:35 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://cae150e0be146bca23b3e3bb2ed7438623cf7c5f-chi-pr.enterprise.ctl.io" target="_blank"> https://cae150e0be146bca23b3e3bb2ed7438623cf7c5f-chi-pr.enterprise.ctl.io </a>

2020-12-16 19:35 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1662/ for more details.

2020-12-17 18:04 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://3de8bf900ba299291147a62da4b9d783662be4b8-chi-pr.enterprise.ctl.io" target="_blank"> https://3de8bf900ba299291147a62da4b9d783662be4b8-chi-pr.enterprise.ctl.io </a>

2020-12-17 18:05 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1664/ for more details.

2020-12-17 19:26 UTC, mattnickles approved these changes

2020-12-18 15:31 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://2dcbeba8f3628ab39e97e6ebdbb060e91bf687a7-chi-pr.enterprise.ctl.io" target="_blank"> https://2dcbeba8f3628ab39e97e6ebdbb060e91bf687a7-chi-pr.enterprise.ctl.io </a>

2020-12-18 15:31 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1669/ for more details.

2020-12-18 17:48 UTC, merged

2020-12-18 17:48 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-ixg7ok, https://ops.elasticbox.com/services/instances/i-05nw6i, https://ops.elasticbox.com/services/instances/i-cl8kr4, https://ops.elasticbox.com/services/instances/i-sk4wti, https://ops.elasticbox.com/services/instances/i-awuar8, https://ops.elasticbox.com/services/instances/i-sl6n0j, https://ops.elasticbox.com/services/instances/i-2rwxv7, https://ops.elasticbox.com/services/instances/i-l7djiv, https://ops.elasticbox.com/services/instances/i-d1uxzy, https://ops.elasticbox.com/services/instances/i-8vf9j8