[FSPE-6062] E2E test for Chi Drawer component functionality -- peer r…
CenturyLinkCloud/ux-chi pull request #723
Opened 2020-10-13 08:06 UTC by joshua22-11

…eview -- do not merge

2020-10-13 08:29 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://65be91c3c4d66f04dc8698c9f3d22991ced8056d-chi-pr.enterprise.ctl.io" target="_blank"> https://65be91c3c4d66f04dc8698c9f3d22991ced8056d-chi-pr.enterprise.ctl.io </a>

2020-10-13 08:30 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1330/ for more details.

2020-10-13 10:45 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://7557e94e3c99702cd5193188d4051da85fa9b881-chi-pr.enterprise.ctl.io" target="_blank"> https://7557e94e3c99702cd5193188d4051da85fa9b881-chi-pr.enterprise.ctl.io </a>

2020-10-13 10:46 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1333/ for more details.

2020-10-13 23:00 UTC, janibolkvadze requested changes
The overall structure looks good. There are some false positives related to clicking the "X" button to close the drawer and also some restructuring is necessary. Thank you!

2020-10-15 10:10 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://629a6eb38e76409be865f1c488a8e3da3437ce23-chi-pr.enterprise.ctl.io" target="_blank"> https://629a6eb38e76409be865f1c488a8e3da3437ce23-chi-pr.enterprise.ctl.io </a>

2020-10-15 10:10 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1360/ for more details.

2020-10-15 10:54 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://2a1c91ce51fbd4eb7754f83be4a925fa9915deca-chi-pr.enterprise.ctl.io" target="_blank"> https://2a1c91ce51fbd4eb7754f83be4a925fa9915deca-chi-pr.enterprise.ctl.io </a>

2020-10-15 10:54 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1378/ for more details.

2020-10-15 11:19 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://07eb99a890e760f29cb631edb9ef582fbafdc924-chi-pr.enterprise.ctl.io" target="_blank"> https://07eb99a890e760f29cb631edb9ef582fbafdc924-chi-pr.enterprise.ctl.io </a>

2020-10-15 11:20 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1384/ for more details.

2020-10-15 21:16 UTC, janibolkvadze requested changes
A minor restructuring of test groups is needed and it will be perfect. Thank you!

2020-10-15 21:16 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +  describe('check that click on "X" in left menu drawer, closes drawer', () => {
Technically you are testing Open and Close as well. Let's tweak the context of the test group:
```suggestion
  describe('Test open & close behavior of Left positioned Drawer', () => {
```

And inside the describe statement let's add 2 test cases as split scenarios of Open and Close. Something like this:

```
describe('Test open & close behavior of Left positioned Drawer',()=>{
  it('Click on Drawer trigger opens the Drawer', () => {
    /*  */
  });

  it('Click on X button closes the Drawer', () => {
  /*  */
  });
});
```
Basically, split the following test assertions into 2: Open and Close.

2020-10-15 21:16 UTC, janibolkvadze commented on test/chi/js/chi-drawer.pug
> +script.
Let's move all the JS scripts to the bottom of the page inside one consolidated `script.`, please

2020-10-16 10:00 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://2c6862d608eb37bbba5735bf2f4dc531c45fe2ea-chi-pr.enterprise.ctl.io" target="_blank"> https://2c6862d608eb37bbba5735bf2f4dc531c45fe2ea-chi-pr.enterprise.ctl.io </a>

2020-10-16 10:00 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1426/ for more details.

2020-10-19 09:58 UTC, janibolkvadze requested changes

2020-10-19 09:58 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +        .get('#drawer-1')
Is this line necessary? I think the current selector is the same element, right?

2020-10-19 09:58 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +    it('Click on X button closes the Drawer and check for other functionalities', () => {
```suggestion
    it('Click on X button closes the Drawer', () => {
```

2020-10-19 09:58 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +        .should('have.class', '-left')
```suggestion
```
This is checking if the class is present in HTML markup.
The proper test would be to check if `left: 0;` CSS is present.
Please use
`.should('have.css' . . .);`

2020-10-27 13:01 UTC, janibolkvadze commented
@joshua22-11 Probably rebase from master went wrong because I see commits and file changes from merged PRs. Can you try to rebase again to see if this can be cleaned? The current state makes it difficult to review PR related changes

2020-11-02 06:59 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://d3f639103e72bb6678eccafabf620fdcb517fa6a-chi-pr.enterprise.ctl.io" target="_blank"> https://d3f639103e72bb6678eccafabf620fdcb517fa6a-chi-pr.enterprise.ctl.io </a>

2020-11-02 06:59 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1537/ for more details.

2020-11-04 13:37 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +        .get('#drawer-1')
```suggestion
```

2020-11-04 13:38 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +    it('Click on X button closes the Drawer and check for other functionalities', () => {
```suggestion
    it('Click on X button closes the Drawer', () => {
```

2020-11-04 13:38 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +    it('Click on X button closes the Drawer and check for other functionalities', () => {
```suggestion
    it('Click on X button closes the Drawer', () => {
```

2020-11-04 13:39 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +      cy.get('#drawer-trigger-11').click();
```suggestion
      cy.get('#drawer-trigger-11')
        .click();
```

2020-11-04 13:39 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +    it('Click on X button closes the Drawer and check for other functionalities', () => {
```suggestion
    it('Click on X button closes the Drawer', () => {
```

2020-11-04 13:39 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +      cy.get('#drawer-trigger-13').click();
```suggestion
      cy.get('#drawer-trigger-13')
        .click();
```

2020-11-04 13:40 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +    it('Click on X button closes the Drawer and check for other functionalities', () => {
```suggestion
    it('Click on X button closes the Drawer', () => {
```

2020-11-04 13:41 UTC, janibolkvadze commented on cypress/integration/chi-js/chi-drawer.spec.js
> +    it('Click on X button closes the Drawer and check for other functionalities', () => {
```suggestion
    it('Click on X button closes the Drawer', () => {
```

2020-11-04 14:06 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://964f9fddf20b952de2860f30bd2dca4f486c7531-chi-pr.enterprise.ctl.io" target="_blank"> https://964f9fddf20b952de2860f30bd2dca4f486c7531-chi-pr.enterprise.ctl.io </a>

2020-11-04 14:07 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1546/ for more details.

2020-11-04 14:10 UTC, janibolkvadze approved these changes

2020-11-04 17:48 UTC, jllr approved these changes

2020-11-04 17:48 UTC, merged

2020-11-04 17:48 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-l153c5, https://ops.elasticbox.com/services/instances/i-fh2wzt, https://ops.elasticbox.com/services/instances/i-05ybdm, https://ops.elasticbox.com/services/instances/i-ln41yq, https://ops.elasticbox.com/services/instances/i-gyzdhz, https://ops.elasticbox.com/services/instances/i-7z12d5, https://ops.elasticbox.com/services/instances/i-cnpu90, https://ops.elasticbox.com/services/instances/i-6nm2hb