[FSPE-6061] -Created E2E test for Chi Popover component functionality - Don't merge. Review needed
CenturyLinkCloud/ux-chi pull request #724
Opened 2020-10-13 09:53 UTC by shintuviswambharan

Create E2E test for Chi Popover component functionality

2020-10-13 09:54 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1331/ for more details.

2020-10-13 10:15 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://86584e9c4db74e5ef6467bc66a90ad8ac9b774b0-chi-pr.enterprise.ctl.io" target="_blank"> https://86584e9c4db74e5ef6467bc66a90ad8ac9b774b0-chi-pr.enterprise.ctl.io </a>

2020-10-13 10:15 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1332/ for more details.

2020-10-13 10:59 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://aa4c2bf32e842a531625686805afb34864f92e72-chi-pr.enterprise.ctl.io" target="_blank"> https://aa4c2bf32e842a531625686805afb34864f92e72-chi-pr.enterprise.ctl.io </a>

2020-10-13 11:00 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1335/ for more details.

2020-10-13 11:45 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://1dd52fd93f2d1fab1ad49789bed00341f6fe4ba0-chi-pr.enterprise.ctl.io" target="_blank"> https://1dd52fd93f2d1fab1ad49789bed00341f6fe4ba0-chi-pr.enterprise.ctl.io </a>

2020-10-13 11:45 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1336/ for more details.

2020-10-13 12:40 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://d14173ae4aee84caa934bbce41d3dbccc470c7c0-chi-pr.enterprise.ctl.io" target="_blank"> https://d14173ae4aee84caa934bbce41d3dbccc470c7c0-chi-pr.enterprise.ctl.io </a>

2020-10-13 12:41 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1338/ for more details.

2020-10-13 22:03 UTC, janibolkvadze requested changes
@shintuviswambharan Looks good! I think it covers well the main scenarios of Popover functionality. Some minor suggestions to improve performance and code linting. Thanks!

2020-10-14 07:08 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1344/ for more details.

2020-10-14 07:12 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1345/ for more details.

2020-10-14 07:32 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://8125a268f3477cf2daf4bc1e2babeea887a23bd3-chi-pr.enterprise.ctl.io" target="_blank"> https://8125a268f3477cf2daf4bc1e2babeea887a23bd3-chi-pr.enterprise.ctl.io </a>

2020-10-14 07:33 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1346/ for more details.

2020-10-14 09:25 UTC, shintuviswambharan commented on cypress/integration/chi-js/popover.spec.js
> +      this.chidata.popperPositions.forEach(position => {
Thank you

2020-10-14 09:25 UTC, shintuviswambharan commented on cypress/integration/chi-js/popover.spec.js
> +        .find('+ .chi-popover')
Updated in latest commit

2020-10-14 09:25 UTC, shintuviswambharan commented on cypress/integration/chi-js/popover.spec.js
> +      cy.get('button.chi-button')
Updated in latest commit

2020-10-14 09:25 UTC, shintuviswambharan commented on cypress/integration/chi-js/popover.spec.js
> +    cy.visit('http://localhost:8000/tests/js/popover.html');
Updated in latest commit

2020-10-14 09:25 UTC, shintuviswambharan commented on test/chi/js/popover.pug
> +    preventAutoHide: true
Updated in latest commit

2020-10-14 09:26 UTC, shintuviswambharan commented on cypress/integration/chi-js/popover.spec.js
> +          .scrollIntoView()
Updated in latest commit

2020-10-14 09:26 UTC, shintuviswambharan commented on test/chi/js/popover.pug
> +    popover.toggle()
Updated in latest commit

2020-10-14 09:26 UTC, shintuviswambharan commented on test/chi/js/popover.pug
> +    popover.hide()
Updated in latest commit

2020-10-14 09:45 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://15edb7112f0f2b20ccc36b68ee792d8b824db61a-chi-pr.enterprise.ctl.io" target="_blank"> https://15edb7112f0f2b20ccc36b68ee792d8b824db61a-chi-pr.enterprise.ctl.io </a>

2020-10-14 09:45 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1348/ for more details.

2020-10-14 12:33 UTC, shintuviswambharan commented
@janibolkvadze , I have updated test cases based on the review comments . Could you please review the same

2020-10-14 21:36 UTC, janibolkvadze requested changes

2020-10-14 21:36 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +  });
```suggestion
  });

```

2020-10-14 21:36 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +    });
```suggestion
    });

```

2020-10-14 21:36 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +         .find('.chi-popover#chi-popover-13')
```suggestion
       .should('have.class', '-active')
       .click(500, 0, {force: true})
       .find('.chi-popover#chi-popover-13')
```

2020-10-14 21:36 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +      //trigger show
```suggestion
```

2020-10-14 21:36 UTC, janibolkvadze commented on test/chi/js/popover.pug
> +// Method 1 - Data Target
Let's remove all the comments, please.

2020-10-14 21:36 UTC, janibolkvadze commented on test/chi/js/popover.pug
> +script.
Let's consolidate `chi.popover()` inside one `script.` on the button of the pug file

2020-10-14 21:36 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +  describe('Hide, Toggle, Show events should work ', function() {
```suggestion
  describe('Hide, Toggle, Show methods should work ', function() {
```

2020-10-14 21:36 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +  describe('Hide, Toggle, Show events should work ', function() {
The click events call the .show(), .hide(), .toggle() methods.
Regarding events: Can we add test cases to check event emission of:
**chi.popover.show
chi.popover.hide** ?
Popover is supposed to emit these events when show and hide are triggered. Would be nice to test that as well.

2020-10-15 09:32 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://0a7473cc6b4186bd7d6b49317155ae2b41a5d073-chi-pr.enterprise.ctl.io" target="_blank"> https://0a7473cc6b4186bd7d6b49317155ae2b41a5d073-chi-pr.enterprise.ctl.io </a>

2020-10-15 09:33 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1358/ for more details.

2020-10-15 09:58 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://ff7430a4789a8140d4c34183fe78e11a22a62720-chi-pr.enterprise.ctl.io" target="_blank"> https://ff7430a4789a8140d4c34183fe78e11a22a62720-chi-pr.enterprise.ctl.io </a>

2020-10-15 09:58 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1359/ for more details.

2020-10-15 11:52 UTC, shintuviswambharan commented on test/chi/js/popover.pug
> +// Method 1 - Data Target
updated in latest commit

2020-10-15 12:22 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://3172c60d3bef9bbacb8a2acfc80cfd582ee7852b-chi-pr.enterprise.ctl.io" target="_blank"> https://3172c60d3bef9bbacb8a2acfc80cfd582ee7852b-chi-pr.enterprise.ctl.io </a>

2020-10-15 12:22 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1387/ for more details.

2020-10-15 20:55 UTC, janibolkvadze reviewed
Just a couple of minor tweakings and it will be perfect. Thank you!

2020-10-15 20:55 UTC, janibolkvadze commented on test/chi/js/popover.pug
> +        button.chi-button.popover-btn(data-position=`${side}`, data-popover-content='<header class="chi-popover__header"><h2 class="chi-popover__title">Popover positioning</h2></header><div class="ch
```suggestion
  div(class=`test-more-${side} -position--relative`,data-cy=`test-more-${side}`)
    button.chi-button.popover-btn(data-position=`${side}`, data-popover-content='<header class="chi-popover__header"><h2 class="chi-popover__title">Popover positioning</h2></header><div class="chi-popover__content"><p class="chi-popover__text">Popover Content.</p></div>')=`${side} popover`
```

2020-10-15 20:55 UTC, janibolkvadze commented on test/chi/js/popover.pug
> +
```suggestion
```

2020-10-15 20:55 UTC, janibolkvadze commented on test/chi/js/popover.pug
> +  script.
Can we move all the JS to the bottom of the file?
Let's consolidate all the scripts together, please.

2020-10-15 20:55 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +        cy.get(getValue)
```suggestion

        cy.get(getValue)
```

2020-10-15 20:55 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +
```suggestion
```

2020-10-15 20:55 UTC, janibolkvadze commented on cypress/integration/chi-js/popover.spec.js
> +
```suggestion
```

2020-10-16 04:47 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1393/ for more details.

2020-10-16 05:26 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://aedb1fbb7203634ec3028d09e2ac69ae7e2c7359-chi-pr.enterprise.ctl.io" target="_blank"> https://aedb1fbb7203634ec3028d09e2ac69ae7e2c7359-chi-pr.enterprise.ctl.io </a>

2020-10-16 05:27 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1398/ for more details.

2020-10-16 05:51 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1403/ for more details.

2020-10-16 07:01 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1416/ for more details.

2020-10-16 07:05 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1417/ for more details.

2020-10-16 07:06 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1418/ for more details.

2020-10-16 07:37 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f3190f0e4495737ead7864506fa2d22a7ddd5b85-chi-pr.enterprise.ctl.io" target="_blank"> https://f3190f0e4495737ead7864506fa2d22a7ddd5b85-chi-pr.enterprise.ctl.io </a>

2020-10-16 07:38 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1419/ for more details.

2020-10-16 12:14 UTC, shintuviswambharan commented
@janibolkvadze , Made the changes based on the review comments. Thank you

2020-10-19 10:04 UTC, janibolkvadze approved these changes
Awesome, thank you!

2020-10-20 11:13 UTC, merged

2020-10-20 11:13 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-akwsq6, https://ops.elasticbox.com/services/instances/i-3lqthe, https://ops.elasticbox.com/services/instances/i-510zda, https://ops.elasticbox.com/services/instances/i-wehf79, https://ops.elasticbox.com/services/instances/i-kolf5c, https://ops.elasticbox.com/services/instances/i-vqsu5t, https://ops.elasticbox.com/services/instances/i-jwg94i, https://ops.elasticbox.com/services/instances/i-qwxa1r, https://ops.elasticbox.com/services/instances/i-fz9ec9, https://ops.elasticbox.com/services/instances/i-txh3bs, https://ops.elasticbox.com/services/instances/i-7ie86i