[FSPE-6283] Add support of Vue & Stencil boilerplates
CenturyLinkCloud/ux-chi pull request #726
Opened 2020-10-13 15:43 UTC by janibolkvadze

### Commit summary

- [x] Implemented Vue boilerplate
- [x] Implemented Stencil boilerplate
- [x] Automated zipping of Vue & Stencil boilerplates making them downloadable
- [x] Documented Framework boilerplates section on the Installation page

Pending:
- [ ] Implement Angular boilerplate
- [ ] Implement React boilerplate

https://ctl.atlassian.net/browse/FSPE-6283

2020-10-13 16:08 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://11d99d3eee6b9c5c6e4e7405cff08cc607740340-chi-pr.enterprise.ctl.io" target="_blank"> https://11d99d3eee6b9c5c6e4e7405cff08cc607740340-chi-pr.enterprise.ctl.io </a>

2020-10-13 16:08 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1340/ for more details.

2020-10-13 20:56 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1341/ for more details.

2020-10-13 21:19 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://0e7f111576700082ce456cc84bc5bdb37a951548-chi-pr.enterprise.ctl.io" target="_blank"> https://0e7f111576700082ce456cc84bc5bdb37a951548-chi-pr.enterprise.ctl.io </a>

2020-10-13 21:20 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1342/ for more details.

2020-10-13 22:32 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://00eeb80c6ae0d031d26f5724aa92d2789f788a54-chi-pr.enterprise.ctl.io" target="_blank"> https://00eeb80c6ae0d031d26f5724aa92d2789f788a54-chi-pr.enterprise.ctl.io </a>

2020-10-13 22:32 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1343/ for more details.

2020-10-14 18:42 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f5f6ac1f1647709eb1941663a823a5912a6b1573-chi-pr.enterprise.ctl.io" target="_blank"> https://f5f6ac1f1647709eb1941663a823a5912a6b1573-chi-pr.enterprise.ctl.io </a>

2020-10-14 18:43 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1352/ for more details.

2020-10-15 14:25 UTC, SergioQCL requested changes

2020-10-16 16:58 UTC, janibolkvadze commented on src/boilerplates/react/react-boilerplate/src/components/header.tsx
> +	render () {
Good catch, the formatting was wrong. I fixed the indentation and the other suggestions.
I also restructured the Vue boilerplate to make the structure consistent with the other Boilerplates.
Thank you!

2020-10-16 17:27 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://72c42a4fca5cd045a47434eb9f186b6d7e6ff296-chi-pr.enterprise.ctl.io" target="_blank"> https://72c42a4fca5cd045a47434eb9f186b6d7e6ff296-chi-pr.enterprise.ctl.io </a>

2020-10-16 17:28 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1430/ for more details.

2020-10-16 23:54 UTC, janibolkvadze commented
test this please

2020-10-17 00:20 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://fd70ccfb2620243d9dd9f53f37ce6c5cef143635-chi-pr.enterprise.ctl.io" target="_blank"> https://fd70ccfb2620243d9dd9f53f37ce6c5cef143635-chi-pr.enterprise.ctl.io </a>

2020-10-17 00:20 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1433/ for more details.

2020-10-19 11:55 UTC, SergioQCL approved these changes
LGTM

2020-10-21 16:41 UTC, mattnickles reviewed
Might be helpful to style these as a button and add an explicit text label

2020-10-21 16:41 UTC, mattnickles commented on src/website/views/getting-started/installation.pug
> +          i.chi-icon.icon-circle-arrow-down-outline.-sm--2
```suggestion
        a.chi-button(href='/boilerplates/vue-boilerplate.zip')
          .chi-button__content
            i.chi-icon.icon-circle-arrow-down-outline
            span Download
```

2020-10-21 16:41 UTC, mattnickles commented on src/website/views/getting-started/installation.pug
> +          i.chi-icon.icon-circle-arrow-down-outline.-sm--2
```suggestion
        a.chi-button(href='/boilerplates/stencil-boilerplate.zip')
          .chi-button__content
            i.chi-icon.icon-circle-arrow-down-outline
            span Download
```

2020-10-21 16:41 UTC, mattnickles commented on src/website/views/getting-started/installation.pug
> +          i.chi-icon.icon-circle-arrow-down-outline.-sm--2
```suggestion
        a.chi-button(href='/boilerplates/angular-boilerplate.zip')
          .chi-button__content
            i.chi-icon.icon-circle-arrow-down-outline
            span Download
```

2020-10-21 16:41 UTC, mattnickles commented on src/website/views/getting-started/installation.pug
> +          i.chi-icon.icon-circle-arrow-down-outline.-sm--2
```suggestion
        a.chi-button(href='/boilerplates/react-boilerplate.zip')
          .chi-button__content
            i.chi-icon.icon-circle-arrow-down-outline
            span Download
```

2020-10-21 17:01 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://0f5862206ecf5c123e7c980066f5fc3dd9f99d64-chi-pr.enterprise.ctl.io" target="_blank"> https://0f5862206ecf5c123e7c980066f5fc3dd9f99d64-chi-pr.enterprise.ctl.io </a>

2020-10-21 17:02 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1477/ for more details.

2020-10-21 18:04 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://a3c5de3aeb6b2a64a38fd15f1cbca76777009eae-chi-pr.enterprise.ctl.io" target="_blank"> https://a3c5de3aeb6b2a64a38fd15f1cbca76777009eae-chi-pr.enterprise.ctl.io </a>

2020-10-21 18:04 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1478/ for more details.

2020-10-23 14:26 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1493/ for more details.

2020-10-23 14:50 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://44642850fac408df9c8c73a68e940f8c5ba0f70e-chi-pr.enterprise.ctl.io" target="_blank"> https://44642850fac408df9c8c73a68e940f8c5ba0f70e-chi-pr.enterprise.ctl.io </a>

2020-10-23 14:50 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1494/ for more details.

2020-10-23 15:54 UTC, jllr approved these changes

2020-10-23 16:21 UTC, mattnickles approved these changes

2020-10-23 16:21 UTC, merged

2020-10-23 16:21 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-go8kp7, https://ops.elasticbox.com/services/instances/i-8gsywa, https://ops.elasticbox.com/services/instances/i-7bo0qo, https://ops.elasticbox.com/services/instances/i-cwo8nv, https://ops.elasticbox.com/services/instances/i-yp8ptg, https://ops.elasticbox.com/services/instances/i-hhi3x7, https://ops.elasticbox.com/services/instances/i-fwg6gj, https://ops.elasticbox.com/services/instances/i-mx5ny2, https://ops.elasticbox.com/services/instances/i-09k1wv