[FSPE-6495] -Added tooltip to chi header component example .Don't merge, Review needed
CenturyLinkCloud/ux-chi pull request #752
Opened 2020-11-06 09:37 UTC by shintuviswambharan

Added tooltip to chi header component example 
@janibolkvadze  could you please review

2020-11-06 10:01 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://ecdd0645d9895abc13e3c59e2fd7d142eda6a0bd-chi-pr.enterprise.ctl.io" target="_blank"> https://ecdd0645d9895abc13e3c59e2fd7d142eda6a0bd-chi-pr.enterprise.ctl.io </a>

2020-11-06 10:02 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1561/ for more details.

2020-11-10 11:49 UTC, janibolkvadze requested changes

2020-11-10 11:49 UTC, janibolkvadze commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-ImpBar-notification" aria-label="Notifcations" data-tooltip="Notifications")
```suggestion
            button.chi-button.-flat.-icon(id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications")
```

2020-11-10 11:49 UTC, janibolkvadze commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-ImpBar-support" aria-label="Support" data-tooltip="Support")
```suggestion
            button.chi-button.-flat.-icon(id="button-impersonation-support" aria-label="Support" data-tooltip="Support")
```

2020-11-10 11:49 UTC, janibolkvadze commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-ImpBar-notification" aria-label="Notifcations" data-tooltip="Notifications">
```suggestion
              <button class="chi-button -flat -icon" id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications">
```

2020-11-10 11:49 UTC, janibolkvadze commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-ImpBar-support" aria-label="Support" data-tooltip="Notifications">
```suggestion
              <button class="chi-button -flat -icon" id="button-impersonation-support" aria-label="Support" data-tooltip="Notifications">
```

2020-11-10 11:49 UTC, janibolkvadze commented on src/website/views/components/header/_examples.pug
> +        chi.tooltip(document.getElementById('button-ImpBar-support'));
```suggestion
        chi.tooltip(document.getElementById('button-impersonation-notification'));
        chi.tooltip(document.getElementById('button-impersonation-support'));
```

2020-11-10 11:49 UTC, janibolkvadze commented on src/website/views/components/header/_examples.pug
> +      chi.tooltip(document.getElementById('button-ImpBar-support'));
```suggestion
      chi.tooltip(document.getElementById('button-impersonation-notification'));
      chi.tooltip(document.getElementById('button-impersonation-support'));
```

2020-11-10 11:52 UTC, janibolkvadze approved these changes

2020-11-10 12:15 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://c5bc065f9bf302e0ef574e050505295251568d96-chi-pr.enterprise.ctl.io" target="_blank"> https://c5bc065f9bf302e0ef574e050505295251568d96-chi-pr.enterprise.ctl.io </a>

2020-11-10 12:15 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1566/ for more details.

2020-11-10 15:37 UTC, jllr requested changes

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-notification" aria-label="Notifcations" data-tooltip="Notifications")
```suggestion
            button.chi-button.-flat.-icon(id="button-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom")
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-support" aria-label="Support" data-tooltip="Support")
```suggestion
            button.chi-button.-flat.-icon(id="button-support" aria-label="Support" data-tooltip="Support" data-position="bottom")
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-notification" aria-label="Notifcations" data-tooltip="Notifications">
```suggestion
              <button class="chi-button -flat -icon" id="button-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom">
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-support" aria-label="Support" data-tooltip="Support">
```suggestion
              <button class="chi-button -flat -icon" id="button-support" aria-label="Support" data-tooltip="Support" data-position="bottom">
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-nav-notification" aria-label="Notifications" data-tooltip="Notifications")
```suggestion
            button.chi-button.-flat.-icon(id="button-nav-notification" aria-label="Notifications" data-tooltip="Notifications" data-position="bottom")
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-nav-support" aria-label="Support" data-tooltip="Support")
```suggestion
            button.chi-button.-flat.-icon(id="button-nav-support" aria-label="Support" data-tooltip="Support" data-position="bottom")
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-nav-notification" aria-label="Notifcations" data-tooltip="Notifications">
```suggestion
              <button class="chi-button -flat -icon" id="button-nav-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom">
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-nav-support" aria-label="Support" data-tooltip="Support">
```suggestion
              <button class="chi-button -flat -icon" id="button-nav-support" aria-label="Support" data-tooltip="Support" data-position="bottom">
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications")
```suggestion
            button.chi-button.-flat.-icon(id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom")
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-impersonation-support" aria-label="Support" data-tooltip="Support")
```suggestion
            button.chi-button.-flat.-icon(id="button-impersonation-support" aria-label="Support" data-tooltip="Support" data-position="bottom")
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications">
```suggestion
              <button class="chi-button -flat -icon" id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom">
```

2020-11-10 15:37 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-impersonation-support" aria-label="Support" data-tooltip="Notifications">
```suggestion
              <button class="chi-button -flat -icon" id="button-impersonation-support" aria-label="Support" data-tooltip="Notifications" data-position="bottom">
```

2020-11-10 19:11 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://eb9e152f796c52deb421230645724f322becc0d9-chi-pr.enterprise.ctl.io" target="_blank"> https://eb9e152f796c52deb421230645724f322becc0d9-chi-pr.enterprise.ctl.io </a>

2020-11-10 19:11 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1571/ for more details.

2020-11-11 07:08 UTC, jllr requested changes

2020-11-11 07:08 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom")
```suggestion
            button.chi-button.-flat.-icon(id="button-notification" aria-label="Notifications" data-tooltip="Notifications" data-position="bottom")
```

2020-11-11 07:08 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom">
```suggestion
              <button class="chi-button -flat -icon" id="button-notification" aria-label="Notifications" data-tooltip="Notifications" data-position="bottom">
```

2020-11-11 07:08 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-nav-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom">
```suggestion
              <button class="chi-button -flat -icon" id="button-nav-notification" aria-label="Notifications" data-tooltip="Notifications" data-position="bottom">
```

2020-11-11 07:08 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +            button.chi-button.-flat.-icon(id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom")
```suggestion
            button.chi-button.-flat.-icon(id="button-impersonation-notification" aria-label="Notifications" data-tooltip="Notifications" data-position="bottom")
```

2020-11-11 07:08 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-impersonation-notification" aria-label="Notifcations" data-tooltip="Notifications" data-position="bottom">
```suggestion
              <button class="chi-button -flat -icon" id="button-impersonation-notification" aria-label="Notifications" data-tooltip="Notifications" data-position="bottom">
```

2020-11-11 07:08 UTC, jllr commented on src/website/views/components/header/_examples.pug
> +              <button class="chi-button -flat -icon" id="button-impersonation-support" aria-label="Support" data-tooltip="Notifications" data-position="bottom">
```suggestion
              <button class="chi-button -flat -icon" id="button-impersonation-support" aria-label="Support" data-tooltip="Support" data-position="bottom">
```

2020-11-11 07:35 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://d594e6b62b0805d54f68e875c95795c01253249a-chi-pr.enterprise.ctl.io" target="_blank"> https://d594e6b62b0805d54f68e875c95795c01253249a-chi-pr.enterprise.ctl.io </a>

2020-11-11 07:35 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1575/ for more details.

2020-11-11 09:30 UTC, jllr approved these changes

2020-11-11 09:31 UTC, merged

2020-11-11 09:31 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-3ll78k, https://ops.elasticbox.com/services/instances/i-e3gtoz, https://ops.elasticbox.com/services/instances/i-t7hwml, https://ops.elasticbox.com/services/instances/i-qlmvdv