[FSPE-5202]added documentation change-Review Required
CenturyLinkCloud/ux-chi pull request #756
Opened 2020-11-11 12:28 UTC by hanyjohny

2020-11-11 12:53 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://4f446dc173a141c96b77d279c0b21377d655c44b-chi-pr.enterprise.ctl.io" target="_blank"> https://4f446dc173a141c96b77d279c0b21377d655c44b-chi-pr.enterprise.ctl.io </a>

2020-11-11 12:53 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1578/ for more details.

2020-11-17 06:20 UTC, SwathiLingareddy approved these changes
Changes are looking good for me

2020-11-17 06:27 UTC, hanyjohny commented
Hi @SwathiLingareddy , please review this PR

2020-11-17 11:36 UTC, jllr requested changes

2020-11-17 11:36 UTC, jllr commented on src/website/views/getting-started/development-workflow.pug
> +  a(href='https://github.com/CenturyLinkCloud/ux-chi') https://github.com/CenturyLinkCloud/ux-chi
```suggestion
  | In order to set up Chi Development workflow, fork and clone 
  a(href='https://github.com/CenturyLinkCloud/ux-chi' target="_blank") ux-chi
  |  GitHub repository
  
```

2020-11-17 11:56 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1605/ for more details.

2020-11-17 14:57 UTC, janibolkvadze commented
test this please

2020-11-17 15:18 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1607/ for more details.

2020-11-17 18:46 UTC, mattnickles commented
test this please

2020-11-17 18:49 UTC, jllr approved these changes

2020-11-18 07:04 UTC, jllr commented
test this please

2020-11-18 14:59 UTC, jllr commented
test this please

2020-11-18 17:44 UTC, jllr commented
test this please

2020-11-18 18:03 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1609/ for more details.

2020-11-19 11:50 UTC, jllr commented
test this please

2020-11-19 12:10 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1612/ for more details.

2020-11-19 12:24 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1613/ for more details.

2020-11-19 12:46 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f33941aac19166ee505a9fe6aeeb38bbaf82886c-chi-pr.enterprise.ctl.io" target="_blank"> https://f33941aac19166ee505a9fe6aeeb38bbaf82886c-chi-pr.enterprise.ctl.io </a>

2020-11-19 12:46 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1614/ for more details.

2020-11-19 14:47 UTC, jllr requested changes

2020-11-19 14:47 UTC, jllr commented on src/website/views/getting-started/development-workflow.pug
> +  | GitHub repository
```suggestion
  |  GitHub repository
```

2020-11-19 15:09 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://6c3f6c463ccf45d31e2fb0d85523693989c3e557-chi-pr.enterprise.ctl.io" target="_blank"> https://6c3f6c463ccf45d31e2fb0d85523693989c3e557-chi-pr.enterprise.ctl.io </a>

2020-11-19 15:09 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1615/ for more details.

2020-11-19 15:25 UTC, jllr requested changes

2020-11-19 15:25 UTC, jllr commented on src/website/views/getting-started/development-workflow.pug
> +  |  GitHub repository
```suggestion
  |  GitHub repository.
```

2020-11-19 15:47 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f62592c72a5057b43510b24aca58258db866307a-chi-pr.enterprise.ctl.io" target="_blank"> https://f62592c72a5057b43510b24aca58258db866307a-chi-pr.enterprise.ctl.io </a>

2020-11-19 15:47 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1616/ for more details.

2020-11-19 15:58 UTC, jllr approved these changes

2020-11-19 15:58 UTC, merged

2020-11-19 15:58 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-8pyis2, https://ops.elasticbox.com/services/instances/i-6i6u75, https://ops.elasticbox.com/services/instances/i-rbsql6, https://ops.elasticbox.com/services/instances/i-8gxtts