[FSPE-6534] Changed input disabled states
CenturyLinkCloud/ux-chi pull request #759
Opened 2020-11-11 23:17 UTC by mattnickles

https://ctl.atlassian.net/browse/FSPE-6534

* Added: Number input documentation now includes examples for Min, Max, Step, Required, Help, Message, and Error.
* Added: Number input now supports required attribute.
* Changed: File input disabled state is now consistent with button disabled state.
* Changed: Number input expanded disabled state is now consistent with button disabled state.
* Changed: Number input no longer renders semantic border and focus colors when disabled.
* Changed: Text input and Textarea disabled text color has been updated to reflect latest guidelines.
* Changed: Number input documentation text for disabled state has been improved.
* Fixed: Label wrapper label margin-bottom specificity issue.
* Fixed: Base Number Input did not support disabled button styles for min/max scenarios.

2020-11-11 23:32 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1585/ for more details.

2020-11-12 12:36 UTC, janibolkvadze commented
test this please

2020-11-12 13:03 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://20ca98d027bd9a6a85ca1bca2eec475032ca0398-chi-pr.enterprise.ctl.io" target="_blank"> https://20ca98d027bd9a6a85ca1bca2eec475032ca0398-chi-pr.enterprise.ctl.io </a>

2020-11-12 13:03 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1588/ for more details.

2020-11-12 18:05 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://625e4c8f36f6655c1e3587ec39716f92f14e2e5d-chi-pr.enterprise.ctl.io" target="_blank"> https://625e4c8f36f6655c1e3587ec39716f92f14e2e5d-chi-pr.enterprise.ctl.io </a>

2020-11-12 18:05 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1593/ for more details.

2020-11-12 19:29 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://8de984e57cf989cdc309cf3b9043f1843bc74f65-chi-pr.enterprise.ctl.io" target="_blank"> https://8de984e57cf989cdc309cf3b9043f1843bc74f65-chi-pr.enterprise.ctl.io </a>

2020-11-12 19:29 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1595/ for more details.

2020-11-12 19:31 UTC, jllr approved these changes

2020-11-12 20:20 UTC, janibolkvadze requested changes

2020-11-12 20:20 UTC, janibolkvadze commented on src/website/views/components/forms/number-input/_examples.pug
> +      <script>chi.popover(document.getElementById('example__help-button'));</script>
```suggestion
      <script>
        document
          .querySelector("#example__help-button")
          .addEventListener("click", function () {
            var popoverElem = document.querySelector("#example__help-popover");

            popoverElem.toggle();
          });
      </script>
```

2020-11-12 21:00 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://a9f54559cec1589c944d94229166350ff7b1faf9-chi-pr.enterprise.ctl.io" target="_blank"> https://a9f54559cec1589c944d94229166350ff7b1faf9-chi-pr.enterprise.ctl.io </a>

2020-11-12 21:01 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1596/ for more details.

2020-11-12 21:41 UTC, janibolkvadze approved these changes

2020-11-12 22:00 UTC, merged

2020-11-12 22:00 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-6w6cds, https://ops.elasticbox.com/services/instances/i-imi73r, https://ops.elasticbox.com/services/instances/i-ppkuyz, https://ops.elasticbox.com/services/instances/i-vk5yh7