[FSPE-6621] Added Popover open  on hover example
CenturyLinkCloud/ux-chi pull request #768
Opened 2020-11-20 14:41 UTC by janibolkvadze

[FSPE-6621] Added Popover open  on hover example

2020-11-20 14:47 UTC, allyourbotsarebelongtous commented
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1619/ for more details.

2020-11-20 15:12 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://2398e0210c43702de8af3934bb34e97f770b6110-chi-pr.enterprise.ctl.io" target="_blank"> https://2398e0210c43702de8af3934bb34e97f770b6110-chi-pr.enterprise.ctl.io </a>

2020-11-20 15:13 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1620/ for more details.

2020-11-20 18:16 UTC, mattnickles requested changes
@janibolkvadze One minor issue - the Popover is not showing when using key commands. Behavior should match the drop down hover example.

2020-11-20 20:07 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://9263ffd8cd1cff6d8107f68b36994ae59aa624e2-chi-pr.enterprise.ctl.io" target="_blank"> https://9263ffd8cd1cff6d8107f68b36994ae59aa624e2-chi-pr.enterprise.ctl.io </a>

2020-11-20 20:08 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1622/ for more details.

2020-11-23 15:02 UTC, jllr commented on src/website/views/components/popover/_examples.pug
> +h3 Open on hover
@janibolkvadze examples are not working on IE11, maybe it's related to JS arrow function.

2020-11-23 15:56 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://6c855198fbde59549ea1a79cad911cc18229b960-chi-pr.enterprise.ctl.io" target="_blank"> https://6c855198fbde59549ea1a79cad911cc18229b960-chi-pr.enterprise.ctl.io </a>

2020-11-23 15:57 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1627/ for more details.

2020-11-23 17:36 UTC, jllr approved these changes

2020-11-23 18:31 UTC, mattnickles approved these changes

2020-11-23 18:32 UTC, merged

2020-11-23 18:32 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-07ixm8, https://ops.elasticbox.com/services/instances/i-7dkelv, https://ops.elasticbox.com/services/instances/i-79ki0o