[FSPE-6599] Added flex-basis to Flex utilities
CenturyLinkCloud/ux-chi pull request #771
Opened 2020-11-30 13:01 UTC by jllr

https://ctl.atlassian.net/browse/FSPE-6599

2020-11-30 13:26 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://bea9143a7bdca3e3959ecceb7f7a1857b2ccfe40-chi-pr.enterprise.ctl.io" target="_blank"> https://bea9143a7bdca3e3959ecceb7f7a1857b2ccfe40-chi-pr.enterprise.ctl.io </a>

2020-11-30 13:27 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1635/ for more details.

2020-12-01 18:46 UTC, mattnickles requested changes

2020-12-01 18:46 UTC, mattnickles commented on src/website/views/utilities/flex.pug
> +p.-text Use the <code>.-flex--basis*</code> class to specifies the initial size of the flex item, before any available space is distributed according to the flex factors.
```suggestion
p.-text Use the <code>.-flex--basis*</code> class to specify the initial size of the flex item, before any available space is distributed according to the flex factors.
```

2020-12-01 19:03 UTC, allyourbotsarebelongtous commented
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1641/ for more details.

2020-12-02 09:26 UTC, jllr commented
test this please

2020-12-02 09:52 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://159e96417c37bcf20f3b3c277894bad73dff362d-chi-pr.enterprise.ctl.io" target="_blank"> https://159e96417c37bcf20f3b3c277894bad73dff362d-chi-pr.enterprise.ctl.io </a>

2020-12-02 09:52 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1645/ for more details.

2020-12-02 14:44 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://91fdeac60fe2ce690babffe4fef185f62a981f6d-chi-pr.enterprise.ctl.io" target="_blank"> https://91fdeac60fe2ce690babffe4fef185f62a981f6d-chi-pr.enterprise.ctl.io </a>

2020-12-02 14:44 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1648/ for more details.

2020-12-02 16:55 UTC, mattnickles approved these changes

2020-12-03 14:33 UTC, janibolkvadze approved these changes

2020-12-03 15:58 UTC, merged

2020-12-03 15:58 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-gwge3y, https://ops.elasticbox.com/services/instances/i-pep4fo, https://ops.elasticbox.com/services/instances/i-qsl0w5