[FSPE-3448] implement Chi time & Chi Time Picker web components
CenturyLinkCloud/ux-chi pull request #780
Opened 2020-12-15 23:33 UTC by janibolkvadze

### Commit Summary

- [x] Implemented Time Web Component
- [x] Implemented Time Picker Web Component
- [x] Updated Time Picker component documentation examples

### Pending
- [ ] Submitting of updated time
- [ ] Automatic scrolling to the active time periods
- [ ] Support of Date Picker with Time example

2020-12-15 23:58 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://8f28366b7aa20c75f6a503066dff708720fec46b-chi-pr.enterprise.ctl.io" target="_blank"> https://8f28366b7aa20c75f6a503066dff708720fec46b-chi-pr.enterprise.ctl.io </a>

2020-12-15 23:58 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1661/ for more details.

2020-12-17 02:09 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://63fdc76c7f810d46ff41d08d20ffde462216ed4f-chi-pr.enterprise.ctl.io" target="_blank"> https://63fdc76c7f810d46ff41d08d20ffde462216ed4f-chi-pr.enterprise.ctl.io </a>

2020-12-17 02:10 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1663/ for more details.

2020-12-17 19:20 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://efc42f0cfa41f8c3a0ca6cee89b69c109561c28c-chi-pr.enterprise.ctl.io" target="_blank"> https://efc42f0cfa41f8c3a0ca6cee89b69c109561c28c-chi-pr.enterprise.ctl.io </a>

2020-12-17 19:21 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1665/ for more details.

2020-12-17 19:40 UTC, mattnickles commented on src/website/views/components/time-picker/_examples.pug
> +      chi-time-picker(id="time-picker-base" display-seconds)
```suggestion
      chi-time-picker(id="time-picker-base")
```

2020-12-17 19:45 UTC, mattnickles commented on src/website/views/components/time-picker/_examples.pug
> +      chi-time-picker#unique-id-va1(value='09:00:00')
Minor inconsistency - value has seconds but seconds column is not displayed in the drop down menu

2020-12-17 19:51 UTC, mattnickles commented on src/website/views/components/time-picker/_examples.pug
> +  | Specify which hours to disable by using the <code>excluded-hours</code> attribute.
```suggestion
  | Specify which times to exclude by using the <code>excluded-hours</code> attribute to exclude hours, <code>excluded-minutes</code> to exclude minutes, and <code>excluded-seconds</code> to exclude seconds.
```

2020-12-17 19:59 UTC, mattnickles commented on src/custom-elements/src/components/date-picker/date-picker.tsx
> +        ${this.time ? '-time' : ''}`}>
If time attribute is specified, can we change placeholder text to `MM/DD/YYYY, --:-- --`

2020-12-18 14:29 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://0409596504ffcd964544a2415d966860e720772a-chi-pr.enterprise.ctl.io" target="_blank"> https://0409596504ffcd964544a2415d966860e720772a-chi-pr.enterprise.ctl.io </a>

2020-12-18 14:29 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1668/ for more details.

2020-12-18 19:21 UTC, SergioQCL requested changes

2020-12-18 19:21 UTC, SergioQCL commented on src/custom-elements/src/components/date-picker/date-picker.tsx
> +        const hours = parseInt(time[0]) >= 12 ? parseInt(time[0]) - 12 : parseInt(time[0]);
I've seen other checks in which you compare time > 12 instead of time >= 12..Which is the correct one?

2020-12-18 19:21 UTC, SergioQCL commented on src/custom-elements/src/components/time/time.tsx
> +  updateExcludedHours() {
Suggestion: It would be nice to have the returning function types

2020-12-20 23:22 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f2d10e8a1bb9aebe09195089f675455fb3f50970-chi-pr.enterprise.ctl.io" target="_blank"> https://f2d10e8a1bb9aebe09195089f675455fb3f50970-chi-pr.enterprise.ctl.io </a>

2020-12-20 23:23 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1671/ for more details.

2020-12-21 08:22 UTC, dani-cl-madrid requested changes

2020-12-21 08:22 UTC, dani-cl-madrid commented on src/custom-elements/src/components/time-picker/time-picker.tsx
> +    }, 50);
Use constant when possible, please.

2020-12-21 12:31 UTC, janibolkvadze commented on src/custom-elements/src/components/date-picker/date-picker.tsx
> +          class={`chi-input__wrapper -icon--right
Good catch, I had conditional class name there but then I did some restructuring and did not change {` back.

2020-12-21 18:31 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f503f6dd9b531f7a30212f22d8b35168cf3404bf-chi-pr.enterprise.ctl.io" target="_blank"> https://f503f6dd9b531f7a30212f22d8b35168cf3404bf-chi-pr.enterprise.ctl.io </a>

2020-12-21 18:31 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1672/ for more details.

2020-12-21 21:32 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://280fd3328b36be316dc7434a9ad7790961e9e128-chi-pr.enterprise.ctl.io" target="_blank"> https://280fd3328b36be316dc7434a9ad7790961e9e128-chi-pr.enterprise.ctl.io </a>

2020-12-21 21:32 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1674/ for more details.

2020-12-21 22:18 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://c3c3047232b0be8dc7bb9b66d265adbc9ef7f3eb-chi-pr.enterprise.ctl.io" target="_blank"> https://c3c3047232b0be8dc7bb9b66d265adbc9ef7f3eb-chi-pr.enterprise.ctl.io </a>

2020-12-21 22:19 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1675/ for more details.

2020-12-22 11:04 UTC, dani-cl-madrid approved these changes
ACK

2020-12-22 12:15 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://fce300eb47b7529dffceabe78460647e2ae86266-chi-pr.enterprise.ctl.io" target="_blank"> https://fce300eb47b7529dffceabe78460647e2ae86266-chi-pr.enterprise.ctl.io </a>

2020-12-22 12:16 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1677/ for more details.

2020-12-22 14:08 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://6a2a85e0e6f9d9c2b35c2f7095923774ebd95f2e-chi-pr.enterprise.ctl.io" target="_blank"> https://6a2a85e0e6f9d9c2b35c2f7095923774ebd95f2e-chi-pr.enterprise.ctl.io </a>

2020-12-22 14:08 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1679/ for more details.

2020-12-22 14:13 UTC, merged

2020-12-22 14:13 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-v8g8hl, https://ops.elasticbox.com/services/instances/i-eyhcu9, https://ops.elasticbox.com/services/instances/i-0riuo3, https://ops.elasticbox.com/services/instances/i-ph8p01, https://ops.elasticbox.com/services/instances/i-jtb858, https://ops.elasticbox.com/services/instances/i-aza7we, https://ops.elasticbox.com/services/instances/i-x80uf4, https://ops.elasticbox.com/services/instances/i-8ckuez, https://ops.elasticbox.com/services/instances/i-nmvcmn, https://ops.elasticbox.com/services/instances/i-2anp9p