Added support of keyboard control to Tabs
CenturyLinkCloud/ux-chi pull request #791
Opened 2021-01-15 20:59 UTC by janibolkvadze

https://ctl.atlassian.net/browse/FSPE-4663

@dani-cl-madrid @SergioQCL @mattnickles @jllr 

https://ctl.atlassian.net/browse/FSPE-4663

2021-01-15 21:25 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://f61ce2088b8c98a1eb71e36f2a8eac33864d89d6-chi-pr.enterprise.ctl.io" target="_blank"> https://f61ce2088b8c98a1eb71e36f2a8eac33864d89d6-chi-pr.enterprise.ctl.io </a>

2021-01-15 21:25 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1699/ for more details.

2021-01-18 16:40 UTC, jllr approved these changes

2021-01-19 10:52 UTC, SergioQCL requested changes

2021-01-19 10:52 UTC, SergioQCL commented on src/chi/javascript/components/tab.js
> +      activeTabIndex = Array.from(this._tabs).indexOf(this.getActiveTab());
Please, define one const per row.

2021-01-21 13:09 UTC, janibolkvadze commented on src/chi/javascript/components/tab.js
> +      activeTabIndex = Array.from(this._tabs).indexOf(this.getActiveTab());
Done 😉

2021-01-21 13:33 UTC, allyourbotsarebelongtous commented
Your CHI Pull Request website is available for review at <a href="https://bf3c3f0e5736de076666ffa0cc3a77c43044e3ee-chi-pr.enterprise.ctl.io" target="_blank"> https://bf3c3f0e5736de076666ffa0cc3a77c43044e3ee-chi-pr.enterprise.ctl.io </a>

2021-01-21 13:34 UTC, allyourbotsarebelongtous commented
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1718/ for more details.

2021-01-21 14:09 UTC, SergioQCL approved these changes
ACK

2021-01-21 18:32 UTC, mattnickles approved these changes

2021-01-21 18:33 UTC, merged

2021-01-21 18:33 UTC, allyourbotsarebelongtous commented
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-lxkiwm, https://ops.elasticbox.com/services/instances/i-19qqyr